### ISSUE TITLE
Server => AppID Incorrect

### ISSUE THREAD

**Issue by kkm** [dsyomichev/source-server-query#6]
var info = await query.info("5.101.166.201", 27015, 2000);
Usually ARK app id is 346110
but your query shows 1313427031.

**Comment by dsyomichev** [comment]
I believe this is due to a new implementation of the info request. I’m
working on an updated version currently.

**Comment by dsyomichev** [comment]
Hi,

I recently updated the package, and after looking at it, this is actually
by design of the query. You can read about it at
https://developer.valvesoftware.com/wiki/Server_queries. Unfortunately the
query will never respond with the actual Steam AppID of the game being
played. However, this value was actually being represented incorrectly, as
it is actually a 64 bit integer. I believe it could be possible to pull out
the AppID from the gameid value using a library like LongJS. See the note
next to the gameID point in the above link.

**Comment by dsyomichev** [comment]
So actually I was completely wrong, sorry about that. The library I was using to read the packets was messing up the string terminators so all the values were off. It should display the appid in the `id` and possibly `steamid` properties.

**Comment by kkm** [comment]
![image](https://user-images.githubusercontent.com/134290/204119489-545e411b-9f09-482f-8de9-b5c9d4d9a336.png)
last charakter with n. it is buggy with json.

**Comment by dsyomichev** [comment]
This is intentional. JS Numbers are stored as floating points, meaning the maximum value is only 52 bits. Should the server return a 64 bit value, a regular JS number would not suffice. Thus, the value is stored as a [BigInt](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt#static_methods).

Data | Type | Comment
-- | -- | --
GameID | long long | The server's 64-bit GameID. If this is present, a more accurate AppID is present in the low 24 bits. The earlier AppID could have been truncated as it was forced into 16-bit storage.

See BigInt documentation for converting the value to a regular Number.

**Comment by kkm** [comment]
but I can't convert to json, it always came up with an error message, I need to override gameid.
